<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2020

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    points
 */

/**
 * Hook class.
 */
class Hook_points_daily
{
    /**
     * Get total points earned from daily membership; some of these will probably have been spent already.
     *
     * @param  MEMBER $member_id The ID of the member we are getting points for
     * @param  TIME $timestamp Time to get for
     * @param  array $point_info The map containing the members point info (fields as enumerated in description) from point_info()
     * @return integer the number of points the member has
     */
    public function total_points(int $member_id, int $timestamp, array $point_info) : int
    {
        $points_per_day = intval(get_option('points_per_day'));
        $points_gained_auto = intval(floor(floatval(time() - $GLOBALS['FORUM_DRIVER']->get_member_join_timestamp($member_id)) / floatval(60 * 60 * 24)));

        if ($timestamp !== null) {
            $points_gained_auto -= min($points_gained_auto, intval(floor(floatval(time() - $timestamp) / floatval(60 * 60 * 24))));
        }

        return $points_per_day * $points_gained_auto;
    }

    /**
     * Calculate points earned to be displayed on POINTS_PROFILE.tpl.
     *
     * @param  MEMBER $member_id_of The ID of the member who is being viewed
     * @param  ?MEMBER $member_id_viewing The ID of the member who is doing the viewing (null: current member)
     * @param  array $point_info The map containing the members point info (fields as enumerated in description) from point_info()
     * @return ?array Point record map containing LABEL, COUNT, POINTS_EACH, and POINTS_TOTAL for use in POINTS_PROFILE.tpl. (null: addon disabled)
     */
    public function points_profile(int $member_id_of, ?int $member_id_viewing, array $point_info) : ?array
    {
        $points_per_day = intval(get_option('points_per_day'));
        $days_joined = intval(floor(floatval(time() - $GLOBALS['FORUM_DRIVER']->get_member_join_timestamp($member_id_of)) / (60.0 * 60.0 * 24.0)));

        return [
            'LABEL' => do_lang('MEMBERSHIP_LENGTH'),
            'COUNT' => integer_format($days_joined),
            'POINTS_EACH' => integer_format($points_per_day),
            'POINTS_TOTAL' => integer_format($days_joined * $points_per_day)
        ];
    }
}
