#!/usr/bin/env php
<?php

chdir(dirname(dirname(__FILE__)));

// Clean up
file_put_contents('data_custom/modules/user_export/out.csv', '');

// Branch-specific handling
switch (git_repos()) {
    /* TODO: We do not want to do this yet on composr.app
    case 'cms_homesite_v11':
        $issues = shell_exec('php delete_alien_files.php git_only');

        if ($issues != '') {
           echo "There seem to be files not expected in this branch, possible cleanup commands are...\n\n" . $issues;
           exit(1);
        }
        break;
    */
}

exit(0);

function git_repos()
{
    $path = __DIR__ . '/.git/HEAD';
    if (!is_file($path)) {
        return '';
    }
    $lines = file($path);
    $parts = explode('/', $lines[0]);
    return trim(end($parts));
}
