application: test-cms
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /data/modules/google_appengine/cloud_storage_proxy\.php.*
  script: data/modules/google_appengine/cloud_storage_proxy.php
- url: /([=]*)pages/(modules|modules\_custom)/([/]*)\.php
  script: \1index.php
- url: /([=]*)pg/s/([^\&\?]*)/index\.php
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)/([^\&\?]*)/index\.php(.*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)/index\.php(.*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/index\.php(.*)
  script: \1index.php
- url: /([=]*)pg/index\.php(.*)
  script: \1index.php
- url: /([=]*)pg/s/([^\&\?]*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)/([^\&\?]*)/
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)/([^\&\?]*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)
  script: \1index.php
- url: /([=]*)pg/s/([^\&\?\.]*)&(.*)
  script: \1index.php
- url: /([=]*)pg/([/\&\?\.]*)/([/\&\?\.]*)/([/\&\?\.]*)&(.*)
  script: \1index.php
- url: /([=]*)pg/([/\&\?\.]*)/([/\&\?\.]*)&(.*)
  script: \1index.php
- url: /([=]*)pg/([/\&\?\.]*)&(.*)
  script: \1index.php
- url: /(site|forum|adminzone|cms|docs)/s/([^\&\?]*)\.htm
  script: \1/index.php
- url: /s/([^\&\?]*)\.htm
  script: index\.php
- url: /(site|forum|adminzone|cms|docs)/([^/\&\?]+)/([^/\&\?]*)/([^\&\?]*)\.htm
  script: \1/index.php
- url: /(site|forum|adminzone|cms|docs)/([^/\&\?]+)/([^/\&\?]*)\.htm
  script: \1/index.php
- url: /(site|forum|adminzone|cms|docs)/([^/\&\?]+)\.htm
  script: \1/index.php
- url: /([^/\&\?]+)/([^/\&\?]*)/([^\&\?]*)\.htm
  script: index.php
- url: /([^/\&\?]+)/([^/\&\?]*)\.htm
  script: index.php
- url: /([^/\&\?]+)\.htm
  script: index.php
#- url: /(site|forum|adminzone|cms|docs)/s/([^\&\?]*)
#  script: \1/index.php
#- url: /s/([^\&\?]*)
#  script: index\.php
#- url: /(site|forum|adminzone|cms|docs)/([^/\&\?]+)/([^/\&\?]*)/([^\&\?]*)
#  script: \1/index.php
#- url: /(site|forum|adminzone|cms|docs)/([^/\&\?]+)/([^/\&\?]*)
#  script: \1/index.php
#- url: /(site|forum|adminzone|cms|docs)/([^/\&\?]+)
#  script: \1/index.php
#- url: /([^/\&\?]+)/([^/\&\?]*)/([^\&\?]*)
#  script: index.php
#- url: /([^/\&\?]+)/([^/\&\?]*)
#  script: index.php
#- url: /([^/\&\?]+)
#  script: index.php
- url: /(.*\.(1st|3g2|3gp|3gp2|3gpp|3p|7z|aac|ai|aif|aifc|aiff|asf|atom|avi|bin|bmp|br|bz2|css|csv|cur|diff|dmg|doc|docx|dot|dotx|eml|exe|f4v|gif|gz|html|ico|ics|ini|iso|jpe|jpeg|jpg|js|json|keynote|log|m2v|m4v|mdb|mid|mov|mp2|mp3|mp4|mpa|mpe|mpeg|mpg|mpv2|numbers|odb|odc|odg|odi|odp|ods|odt|ogg|ogv|otf|pages|patch|pdf|png|ppt|pptx|ps|psd|pub|qt|ra|ram|rar|rm|rss|rtf|sql|svg|swf|tar|tga|tgz|tif|tiff|torrent|tpl|ttf|txt|vsd|vtt|yaml|yml|wav|weba|webm|webp|wma|wmv|woff|woff2|xls|xlsx|xml|xsd|xsl|zip))
  static_files: \1
  upload: .*\.(1st|3g2|3gp|3gp2|3gpp|3p|7z|aac|ai|aif|aifc|aiff|asf|atom|avi|bmp|br|bz2|css|csv|cur|diff|dmg|doc|docx|dot|dotx|eml|exe|f4v|gif|gz|html|ico|ics|ini|iso|jpe|jpeg|jpg|js|json|keynote|log|m2v|m4v|mdb|mid|mov|mp2|mp3|mp4|mpa|mpe|mpeg|mpg|mpv2|numbers|odb|odc|odg|odi|odp|ods|odt|ogg|ogv|otf|pages|patch|pdf|png|ppt|pptx|ps|psd|pub|qt|ra|ram|rar|rm|rss|rtf|sql|svg|tar|tga|tgz|tif|tiff|torrent|tpl|ttf|txt|vsd|vtt|yaml|yml|wav|weba|webm|webp|wma|wmv|woff|woff2|xls|xlsx|xml|xsd|xsl|zip)
  application_readable: true
- url: /
  script: index.php
- url: /adminzone/
  script: adminzone/index.php
- url: /cms/
  script: cms/index.php
- url: /forum/
  script: forum/index.php
- url: /test.php
  script: test.php
- url: /docs/
  script: docs/index.php
- url: /_ah/mail/tickets@appid.appspotmail.com
  script: data/incoming_ticket_email.php
  login: admin
- url: /_ah/bounce
  script: data/incoming_bounced_email.php
  login: admin
- url: /(.*\.php)(/.*)?(\?.*)?
  script: \1
#- url: .*
#  script: 404.htm

skip_files:
- ^uploads/(?<!website_specific/).*
- ^caches/.*
- ^data_custom/errorlog.php$
- ^temp/.*
- ^\.git/.*
- ^data_custom/modules/google_appengine/.*
- ^dump.sql
- ^themes/default/templates_cached/.*
- ^themes/admin/templates_cached/.*
- ^_old/.*

inbound_services:
- mail
- mail_bounce

admin_console:
  pages:
  - name: Admin Zone
    url: /adminzone

pagespeed:
  enabled_rewriters:
  - CollapseWhitespace
  - ElideAttributes
  - RemoveComments
  - RemoveQuotes
  - LeftTrimUrls
  disabled_rewriters:
  - ConvertMetaTags
  - InlineCss
  - InlinePreviewImages
  - CombineCss
  - CombineJs
