USE PlaceHolderForDb;
 
DROP PROCEDURE IF EXISTS add_user ;
 
CREATE PROCEDURE add_user()
BEGIN
DECLARE EXIT HANDLER FOR 1044 BEGIN END;
DECLARE EXIT HANDLER FOR 1410 BEGIN END;
CREATE USER 'PlaceHolderForUser'@'localhost' IDENTIFIED BY 'PlaceHolderForPassword';
GRANT ALL PRIVILEGES ON PlaceHolderForDb.* TO 'PlaceHolderForUser'@'localhost';
FLUSH PRIVILEGES;
END ;

CALL add_user() ;

DROP PROCEDURE IF EXISTS add_user ;
