<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2021

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    search
 */

/**
 * Hook class.
 */
class Hook_contentious_overrides_search
{
    /**
     * Add to a template being compiled.
     *
     * @param  string $data Template data
     * @param  ID_TEXT $template_name The name of the template (blank: not from a file)
     * @param  ID_TEXT $theme The name of the theme
     * @param  ID_TEXT $lang The language it is for
     * @param  ?string $suffix File type suffix of template file (e.g. .tpl) (null: not from a file)
     * @set .tpl .js .xml .txt .css
     * @param  ?string $directory Subdirectory type to look in (null: not from a file)
     * @set templates javascript xml text css
     */
    public function compile_template(&$data, $template_name, $theme, $lang, $suffix, $directory)
    {
        if (($template_name != 'global') || ($suffix != '.js')) {
            return;
        }

        if (!addon_installed('search')) {
            return;
        }

        $j = 'search';
        $found = find_template_place($j, '', $theme, '.js', 'javascript');
        if ($found !== null) {
            $full_path = get_custom_file_base() . '/themes/' . $found[0] . $found[1] . $j . $found[2];
            $data .= cms_file_get_contents_safe($full_path);
        }
    }
}
