<?php /*

 Composr
 Copyright (c) Christopher Graham, 2004-2024

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    leader_board
 */

/**
 * Hook class.
 */
class Hook_actionlog_leader_board extends Hook_actionlog
{
    /**
     * Get details of action log entry types handled by this hook.
     *
     * @return array Map of handler data in standard format
     */
    public function get_handlers() : array
    {
        if (!addon_installed('points') || !addon_installed('leader_board')) {
            return [];
        }

        require_lang('leader_board');

        return [
            'ADD_LEADER_BOARD' => [
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'leader_board',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => [
                    'EDIT_THIS_LEADER_BOARD' => '_SEARCH:admin_leader_board:_edit:{ID}',
                ],
            ],
            'EDIT_LEADER_BOARD' => [
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'leader_board',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => [
                    'EDIT_THIS_LEADER_BOARD' => '_SEARCH:admin_leader_board:_edit:{ID}',
                ],
            ],
            'DELETE_LEADER_BOARD' => [
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'leader_board',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => [
                    'ADD_LEADER_BOARD' => '_SEARCH:admin_leader_board:add',
                ],
            ],
        ];
    }
}
