<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2022

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Helper function for *_text_file.
 *
 * @param  string $codename The file name (without .txt)
 * @param  ?LANGUAGE_NAME $lang The language to load from (null: none) (blank: search)
 * @param  boolean $get_save_path Get the path to save to (may be different to the path found at)
 * @return string The path to the file (blank: not found)
 *
 * @ignore
 */
function _find_text_file_path(string $codename, ?string $lang, bool $get_save_path = false) : string
{
    if ($lang === null) {
        // No language...

        if ($get_save_path) {
            $path = get_file_base(true) . '/text_custom/' . $codename . '.txt';
        }

        $path = get_file_base() . '/text_custom/' . $codename . '.txt';
        if (is_file($path)) {
            return $path;
        }

        $path = get_file_base() . '/text/' . $codename . '.txt';
        if (is_file($path)) {
            return $path;
        }

        return '';
    }

    if ($lang != '') {
        // Specific language
        $langs = [$lang];
    } else {
        // Search languages
        $langs = [user_lang()];
        if (get_site_default_lang() != user_lang()) {
            $langs[] = get_site_default_lang();
        }
        if (fallback_lang() != get_site_default_lang()) {
            $langs[] = fallback_lang();
        }
    }

    if ($get_save_path) {
        $path = get_file_base(true) . '/text_custom/' . $langs[0] . '/' . $codename . '.txt';
    }

    foreach ($langs as $lang) {
        $path = get_file_base() . '/text_custom/' . $lang . '/' . $codename . '.txt';
        if (is_file($path)) {
            return $path;
        }

        $path = get_file_base() . '/text/' . $lang . '/' . $codename . '.txt';
        if (is_file($path)) {
            return $path;
        }
    }

    return '';
}

/**
 * Read a text file, using the _custom system.
 *
 * @param  string $codename The file name (without .txt)
 * @param  ?LANGUAGE_NAME $lang The language to load from (null: none) (blank: search)
 * @param  boolean $missing_blank Whether to tolerate missing files
 * @return string The file contents
 */
function read_text_file(string $codename, ?string $lang = null, bool $missing_blank = false) : string
{
    $path = _find_text_file_path($codename, $lang);

    if (!is_file($path)) {
        if ($lang !== fallback_lang()) {
            return read_text_file($codename, fallback_lang(), $missing_blank);
        }

        if ($missing_blank) {
            return '';
        }
        warn_exit(do_lang_tempcode('MISSING_TEXT_FILE', escape_html($codename), escape_html('text/' . (($lang === null) ? '' : ($lang . '/')) . $codename . '.txt')), false, true);
    }
    $in = cms_file_get_contents_safe($path, FILE_READ_UNIXIFIED_TEXT | FILE_READ_BOM);

    if (strpos($path, '_custom/') === false) {
        global $LANG_FILTER_OB;
        $in = $LANG_FILTER_OB->compile_time(null, $in, $lang);
    }

    return $in;
}

/**
 * Write a text file, using the _custom system.
 *
 * @param  string $codename The file name (without .txt)
 * @param  ?LANGUAGE_NAME $lang The language to write for (null: none) (blank: search)
 * @param  string $out The data to write
 */
function write_text_file(string $codename, ?string $lang, string $out)
{
    $path = _find_text_file_path($codename, $lang, true);

    require_code('files');

    cms_file_put_contents_safe($path, $out, FILE_WRITE_FIX_PERMISSIONS | FILE_WRITE_BOM);

    // Backup with a timestamp (useful if for example an addon update replaces changes)
    $path .= '.' . strval(time());
    cms_file_put_contents_safe($path, $out, FILE_WRITE_FIX_PERMISSIONS | FILE_WRITE_BOM);
}
