<?php

/*

  Composr
  Copyright (c) ocProducts, 2004-2021

  See docs/LICENSE.md for full licensing information.


  NOTE TO PROGRAMMERS:
  Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
 * *** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

 */

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    points
 */

/**
 * Hook class.
 */
class Hook_addon_registry_leader_board
{

    /**
     * Get a list of file permissions to set.
     *
     * @param  boolean $runtime Whether to include wildcards represented runtime-created chmoddable files
     * @return array File permissions to set
     */
    public function get_chmod_array(bool $runtime = false): array
    {
        return [];
    }

    /**
     * Get the version of Composr this addon is for.
     *
     * @return float Version number
     */
    public function get_version(): float
    {
        return cms_version_number();
    }

    /**
     * Get the addon category.
     *
     * @return string The category
     */
    public function get_category(): string
    {
        return 'Fun and Games';
    }

    /**
     * Get the description of the addon.
     *
     * @return string Description of the addon
     */
    public function get_description(): string
    {
        return 'Allow website administrators to display leader-board blocks for members earning the most points.';
    }

    /**
     * Get a list of tutorials that apply to this addon.
     *
     * @return array List of tutorials
     */
    public function get_applicable_tutorials(): array
    {
        return [
            'tut_leader_board', // TODO
        ];
    }

    /**
     * Get a mapping of dependency types.
     *
     * @return array A structure specifying dependency information
     */
    public function get_dependencies(): array
    {
        return [
            'requires' => ["points"],
            'recommends' => [],
            'conflicts_with' => [],
        ];
    }

    /**
     * Explicitly say which icon should be used.
     *
     * @return URLPATH Icon
     */
    public function get_default_icon(): string
    {
        return 'themes/default/images/icons/menu/social/leader_board.svg';
    }

    /**
     * Get a list of files that belong to this addon.
     *
     * @return array List of files
     */
    public function get_file_list(): array
    {
        return [
            'themes/default/images/icons/menu/social/leader_board.svg',
            'themes/default/images/icons_monochrome/menu/social/leader_board.svg',
            'sources/hooks/systems/config/leader_board_start_date.php',
            'sources/hooks/systems/config/leader_board_show_staff.php',
            'sources/hooks/systems/config/leader_board_size.php',
            'sources/hooks/modules/admin_setupwizard/leader_board.php',
            'themes/default/templates/POINTS_LEADER_BOARD.tpl',
            'themes/default/templates/POINTS_LEADER_BOARD_SCREEN.tpl',
            'themes/default/templates/POINTS_LEADER_BOARD_ROW.tpl',
            'themes/default/templates/POINTS_LEADER_BOARD_WEEK.tpl',
            'admin/pages/modules/admin_leader_board.php',
            'site/pages/modules/leader_board.php',
            'sources/blocks/main_leader_board.php',
            'sources/hooks/systems/cron/leader_board.php',
            'sources/leader_board.php',
            'lang/EN/leader_board.ini',
        ];
    }

    /**
     * Get mapping between template names and the method of this class that can render a preview of them.
     *
     * @return array The mapping
     */
    public function tpl_previews(): array
    {
        return [
            'templates/POINTS_LEADER_BOARD_ROW.tpl' => 'points_leader_board',
            'templates/POINTS_LEADER_BOARD.tpl' => 'points_leader_board',
            'templates/POINTS_LEADER_BOARD_WEEK.tpl' => 'points_leader_board_screen',
            'templates/POINTS_LEADER_BOARD_SCREEN.tpl' => 'points_leader_board_screen',
                // TODO
        ];
    }

    // TODO

    /**
     * Get a preview(s) of a (group of) template(s), as a full standalone piece of HTML in Tempcode format.
     * Uses sources/lorem.php functions to place appropriate stock-text. Should not hard-code things, as the code is intended to be declarative.
     * Assumptions: You can assume all Lang/CSS/JavaScript files in this addon have been pre-required.
     *
     * @return Tempcode Preview
     */
    public function tpl_preview__points_leader_board(): object
    {
        $out = new Tempcode();
        foreach (placeholder_array() as $k => $v) {
            $out->attach(do_lorem_template('POINTS_LEADER_BOARD_ROW', [
                'ID' => placeholder_id(),
                'POINTS_URL' => placeholder_url(),
                'PROFILE_URL' => placeholder_url(),
                '_POINTS' => placeholder_number(),
                'POINTS' => placeholder_number(),
                'USERNAME' => lorem_phrase(),
                'HAS_RANK_IMAGES' => true,
            ]));
        }

        return lorem_globalise(do_lorem_template('POINTS_LEADER_BOARD', [
            'URL' => placeholder_url(),
            '_LIMIT' => placeholder_number(),
            'LIMIT' => placeholder_number(),
            'ROWS' => $out,
                ]), null, '', true);
    }

    /**
     * Get a preview(s) of a (group of) template(s), as a full standalone piece of HTML in Tempcode format.
     * Uses sources/lorem.php functions to place appropriate stock-text. Should not hard-code things, as the code is intended to be declarative.
     * Assumptions: You can assume all Lang/CSS/JavaScript files in this addon have been pre-required.
     *
     * @return Tempcode Preview
     */
    public function tpl_preview__points_leader_board_screen(): object
    {
        $out = new Tempcode();
        foreach (placeholder_array() as $k => $v) {
            $week_tpl = new Tempcode();
            foreach (placeholder_array() as $_k => $_v) {
                $week_tpl->attach(do_lorem_template('POINTS_LEADER_BOARD_ROW', [
                    'ID' => placeholder_id(),
                    'POINTS_URL' => placeholder_url(),
                    'PROFILE_URL' => placeholder_url(),
                    '_POINTS' => placeholder_number(),
                    'POINTS' => placeholder_number(),
                    'USERNAME' => lorem_phrase(),
                    'HAS_RANK_IMAGES' => true,
                ]));
            }
            $out->attach(do_lorem_template('POINTS_LEADER_BOARD_WEEK', [
                '_WEEK' => placeholder_number(),
                'WEEK' => placeholder_number(),
                'ROWS' => $week_tpl,
            ]));
        }

        return lorem_globalise(do_lorem_template('POINTS_LEADER_BOARD_SCREEN', [
            'TITLE' => lorem_title(),
            'WEEKS' => $out,
                ]), null, '', true);
    }

}
