<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2020

 See text/EN/licence.txt for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    wordfilter
 */

/**
 * Hook class.
 */
class Hook_addon_registry_wordfilter
{
    /**
     * Get a list of file permissions to set.
     *
     * @param  boolean $runtime Whether to include wildcards represented runtime-created chmoddable files
     * @return array File permissions to set
     */
    public function get_chmod_array($runtime = false)
    {
        return [];
    }

    /**
     * Get the version of Composr this addon is for.
     *
     * @return float Version number
     */
    public function get_version()
    {
        return cms_version_number();
    }

    /**
     * Get the description of the addon.
     *
     * @return string Description of the addon
     */
    public function get_description()
    {
        return 'Block rude/offensive/inappropriate words.';
    }

    /**
     * Get a list of tutorials that apply to this addon.
     *
     * @return array List of tutorials
     */
    public function get_applicable_tutorials()
    {
        return [
            'tut_censor',
        ];
    }

    /**
     * Get a mapping of dependency types.
     *
     * @return array File permissions to set
     */
    public function get_dependencies()
    {
        return [
            'requires' => [],
            'recommends' => [],
            'conflicts_with' => [],
            'previously_in_addon' => ['core_wordfilter'],
        ];
    }

    /**
     * Explicitly say which icon should be used.
     *
     * @return URLPATH Icon
     */
    public function get_default_icon()
    {
        return 'themes/default/images/icons/menu/adminzone/security/wordfilter.svg';
    }

    /**
     * Get a list of files that belong to this addon.
     *
     * @return array List of files
     */
    public function get_file_list()
    {
        return [
            'themes/default/images/icons/menu/adminzone/security/wordfilter.svg',
            'themes/default/images/icons_monochrome/menu/adminzone/security/wordfilter.svg',
            'sources/hooks/systems/addon_registry/wordfilter.php',
            'sources/hooks/systems/page_groupings/wordfilter.php',
            'lang/EN/wordfilter.ini',
            'adminzone/pages/modules/admin_wordfilter.php',
            'sources/hooks/modules/admin_setupwizard/wordfilter.php',
            'sources/hooks/modules/admin_import_types/wordfilter.php',
            'sources/hooks/systems/commandr_fs_extended_config/wordfilter.php',
            'sources/hooks/systems/actionlog/wordfilter.php',
            'themes/default/javascript/wordfilter.js',
        ];
    }
}
