<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2019

 See text/EN/licence.txt for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    calendar
 */

/**
 * Hook class.
 */
class Hook_points_joining
{
    /**
     * Get points earned for creating an account; some of these will probably have been spent already.
     *
     * @param  MEMBER $member_id The ID of the member we are getting points for
     * @param  TIME $timestamp Time to get for (null: now)
     * @param  array $point_info The map containing the members point info (fields as enumerated in description) from point_info()
     * @return integer the number of points the member has
     */
    public function total_points($member_id, $timestamp, $point_info)
    {
        $points_joining = intval(get_option('points_joining'));

        if ($timestamp !== null && $timestamp < $GLOBALS['FORUM_DRIVER']->get_member_join_timestamp($member_id)) {
            $points_joining = 0;
        }

        return $points_joining;
    }

    /**
     * Calculate points earned to be displayed on POINTS_PROFILE.tpl
     *
     * @param  MEMBER $member_id_of The ID of the member who is being viewed
     * @param  ?MEMBER $member_id_viewing The ID of the member who is doing the viewing (null: current member)
     * @param  array $point_info The map containing the members point info (fields as enumerated in description) from point_info()
     * @return array Point record map containing LABEL, COUNT, POINTS_EACH, and POINTS_TOTAL for use in POINTS_PROFILE.tpl.
     */
    public function points_profile($member_id_of, $member_id_viewing, $point_info)
    {
        $points_joining = intval(get_option('points_joining'));

        return [
            'LABEL' => do_lang('JOINING'), 
            'COUNT' => integer_format(1), 
            'POINTS_EACH' => integer_format($points_joining), 
            'POINTS_TOTAL' => integer_format($points_joining)
        ];
    }
}
