{TITLE}

{$PARAGRAPH,{!cms_homesite:COMMON_ERRORS_TEXT}}

{+START,LOOP,ERRORS}
	<h2>{ERROR_MESSAGE*}</h2>
	{$PARAGRAPH,{$COMCODE,{ERROR_SUMMARY}}}

	<h3>{!HOW_DID_THIS_HAPPEN}</h3>
	{$PARAGRAPH,{$COMCODE,{ERROR_CAUSE}}}

	<h3>{!HOW_DO_I_FIX}</h3>
	{$PARAGRAPH,{$COMCODE,{ERROR_RESOLUTION}}}
{+END}