{+START,IF_NON_EMPTY,{PARENT_ID}{REASON}{PENDING_REASON}{MEMO}}
	{+START,SET,tooltip}
		{+START,IF_NON_EMPTY,{PARENT_ID}}<em>{!PARENT_TRANSACTION;}</em>: {PARENT_ID}{+START,IF_NON_EMPTY,{REASON}{PENDING_REASON}{MEMO}}<br />{+END}{+END}
		{+START,IF_NON_EMPTY,{REASON}}<em>{!REASON;}</em>: {REASON}{+START,IF_NON_EMPTY,{PENDING_REASON}{MEMO}}<br />{+END}{+END}
		{+START,IF_NON_EMPTY,{REASON}}<em>{!REASON_FOR_PENDING;}</em>: {PENDING_REASON}{+START,IF_NON_EMPTY,{MEMO}}<br />{+END}{+END}
		{+START,IF_NON_EMPTY,{MEMO}}<em>{!NOTES;}</em>: {MEMO}{+END}
	{+END}
	<span data-cms-tooltip="{ contents: '{$GET;^*,tooltip}', delay: 0 }">{TXN_ID*}</span>
{+END}
{+START,IF_EMPTY,{PARENT_ID}{REASON}{PENDING_REASON}{MEMO}}
	{TXN_ID*}
{+END}
